import type { CelestialSearchItem } from './celestial-catalog';

export const BRIGHT_STARS: CelestialSearchItem[] = [
  {
    aliases: ['天狼', '大犬座α', 'Alpha Canis Majoris', 'Dog Star', 'HIP 32349', 'HP 32349', 'HP32349', 'tianlang', 'tl'],
    category: 'stars',
    constellationEn: 'Canis Major',
    constellationZh: '大犬座',
    designation: 'α CMa / HIP 32349',
    id: 'Sirius',
    nameEn: 'Sirius',
    nameZh: '天狼星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: -1.46,
  },
  {
    aliases: ['老人', '船底座α', 'Alpha Carinae', 'HIP 30438', 'HP 30438', 'HP30438', '寿星', 'laoren', 'lr'],
    category: 'stars',
    constellationEn: 'Carina',
    constellationZh: '船底座',
    designation: 'α Car / HIP 30438',
    id: 'Canopus',
    nameEn: 'Canopus',
    nameZh: '老人星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: -0.74,
  },
  {
    aliases: ['大角', '牧夫座α', 'Alpha Boötis', 'HIP 69673', 'HP 69673', 'HP69673', 'dajiao', 'dj'],
    category: 'stars',
    constellationEn: 'Boötes',
    constellationZh: '牧夫座',
    designation: 'α Boo / HIP 69673',
    id: 'Arcturus',
    nameEn: 'Arcturus',
    nameZh: '大角星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: -0.05,
  },
  {
    aliases: ['南门二', '半人马座α', 'Rigil Kentaurus', 'Alpha Centauri', 'Toliman', 'HIP 71683', 'HP 71683', 'HP71683', 'nanmener', 'nme'],
    category: 'stars',
    constellationEn: 'Centaurus',
    constellationZh: '半人马座',
    designation: 'α Cen / HIP 71683',
    engineIds: ['* alf Cen'],
    id: 'Rigil Kentaurus',
    nameEn: 'Rigil Kentaurus',
    nameZh: '南门二',
    typeEn: 'Star System',
    typeZh: '恒星系统',
    vmag: -0.27,
  },
  {
    aliases: [
      '织女一',
      '天琴座α',
      'Alpha Lyrae',
      'Alpha Lyr',
      'α Lyr',
      'α Lyrae',
      'HIP 91262',
      'HP 91262',
      'HP91262',
      'zhinvxing',
      'znx',
      'zhinv',
      'zn',
    ],
    category: 'stars',
    constellationEn: 'Lyra',
    constellationZh: '天琴座',
    designation: 'α Lyr / HIP 91262',
    id: 'Vega',
    nameEn: 'Vega',
    nameZh: '织女星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.03,
  },
  {
    aliases: [
      '五车二',
      '御夫座α',
      'Alpha Aurigae',
      'Alpha Aur',
      'α Aur',
      'α Aurigae',
      'HIP 24608',
      'HP 24608',
      'HP24608',
      'wucheer',
      'wuch eer',
      'wce',
    ],
    category: 'stars',
    constellationEn: 'Auriga',
    constellationZh: '御夫座',
    designation: 'α Aur / HIP 24608',
    id: 'Capella',
    nameEn: 'Capella',
    nameZh: '五车二',
    typeEn: 'Star System',
    typeZh: '恒星',
    vmag: 0.08,
  },
  {
    aliases: [
      '参宿七',
      '猎户座β',
      'Beta Orionis',
      'Beta Ori',
      'β Ori',
      'β Orionis',
      'HIP 24436',
      'HP 24436',
      'HP24436',
      'shensuqi',
      'cansuqi',
      'ssq',
    ],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'β Ori / HIP 24436',
    id: 'Rigel',
    nameEn: 'Rigel',
    nameZh: '参宿七',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.13,
  },
  {
    aliases: ['南河三', '小犬座α', 'Alpha Canis Minoris', 'HIP 37279', 'HP 37279', 'HP37279', 'nanhesan', 'nhs'],
    category: 'stars',
    constellationEn: 'Canis Minor',
    constellationZh: '小犬座',
    designation: 'α CMi / HIP 37279',
    id: 'Procyon',
    nameEn: 'Procyon',
    nameZh: '南河三',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.34,
  },
  {
    aliases: ['水委一', '波江座α', 'Alpha Eridani', 'HIP 7588', 'HP 7588', 'HP7588', 'shuiweiyi', 'swy'],
    category: 'stars',
    constellationEn: 'Eridanus',
    constellationZh: '波江座',
    designation: 'α Eri / HIP 7588',
    id: 'Achernar',
    nameEn: 'Achernar',
    nameZh: '水委一',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.46,
  },
  {
    aliases: [
      '参宿四',
      '猎户座α',
      'Alpha Orionis',
      'Alpha Ori',
      'α Ori',
      'α Orionis',
      'HIP 27989',
      'HP 27989',
      'HP27989',
      'shensusi',
      'cansusi',
      'sss',
    ],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'α Ori / HIP 27989',
    id: 'Betelgeuse',
    nameEn: 'Betelgeuse',
    nameZh: '参宿四',
    popular: true,
    typeEn: 'Red Supergiant',
    typeZh: '红超巨星',
    vmag: 0.50,
  },
  {
    aliases: ['马腹一', '半人马座β', 'Beta Centauri', 'Hadar', 'HIP 68702', 'HP 68702', 'HP68702', 'mafuyi', 'mfy'],
    category: 'stars',
    constellationEn: 'Centaurus',
    constellationZh: '半人马座',
    designation: 'β Cen / HIP 68702',
    id: 'Hadar',
    nameEn: 'Hadar',
    nameZh: '马腹一',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.61,
  },
  {
    aliases: ['河鼓二', '天鹰座α', 'Alpha Aquilae', 'HIP 97649', 'HP 97649', 'HP97649', '牛郎', 'niulang', 'nl'],
    category: 'stars',
    constellationEn: 'Aquila',
    constellationZh: '天鹰座',
    designation: 'α Aql / HIP 97649',
    id: 'Altair',
    nameEn: 'Altair',
    nameZh: '牛郎星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.77,
  },
  {
    aliases: ['十字架二', '南十字座α', 'Alpha Crucis', 'HIP 60718', 'HP 60718', 'HP60718', 'shizijiaer', 'szje'],
    category: 'stars',
    constellationEn: 'Crux',
    constellationZh: '南十字座',
    designation: 'α Cru / HIP 60718',
    engineIds: ['* alf01 Cru'],
    id: 'Acrux',
    nameEn: 'Acrux',
    nameZh: '十字架二',
    typeEn: 'Star System',
    typeZh: '恒星',
    vmag: 0.76,
  },
  {
    aliases: ['毕宿五', '金牛座α', 'Alpha Tauri', 'HIP 21421', 'HP 21421', 'HP21421', 'bishuwu', 'bsw'],
    category: 'stars',
    constellationEn: 'Taurus',
    constellationZh: '金牛座',
    designation: 'α Tau / HIP 21421',
    id: 'Aldebaran',
    nameEn: 'Aldebaran',
    nameZh: '毕宿五',
    popular: true,
    typeEn: 'Red Giant',
    typeZh: '红巨星',
    vmag: 0.86,
  },
  {
    aliases: ['心宿二', '天蝎座α', 'Alpha Scorpii', '大火', 'HIP 80763', 'HP 80763', 'HP80763', 'xinshuer', 'xse'],
    category: 'stars',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'α Sco / HIP 80763',
    id: 'Antares',
    nameEn: 'Antares',
    nameZh: '心宿二',
    popular: true,
    typeEn: 'Red Supergiant',
    typeZh: '红超巨星',
    vmag: 0.96,
  },
  {
    aliases: ['角宿一', '室女座α', 'Alpha Virginis', 'HIP 65474', 'HP 65474', 'HP65474', 'jiaoshuyi', 'jsy'],
    category: 'stars',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'α Vir / HIP 65474',
    id: 'Spica',
    nameEn: 'Spica',
    nameZh: '角宿一',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 0.97,
  },
  {
    aliases: ['北河三', '双子座β', 'Beta Geminorum', 'HIP 37826', 'HP 37826', 'HP37826', 'beihesan', 'bhs'],
    category: 'stars',
    constellationEn: 'Gemini',
    constellationZh: '双子座',
    designation: 'β Gem / HIP 37826',
    id: 'Pollux',
    nameEn: 'Pollux',
    nameZh: '北河三',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.14,
  },
  {
    aliases: ['北落师门', '南鱼座α', 'Alpha Piscis Austrini', 'HIP 113368', 'HP 113368', 'HP113368', 'beiluoshimen', 'blsm'],
    category: 'stars',
    constellationEn: 'Piscis Austrinus',
    constellationZh: '南鱼座',
    designation: 'α PsA / HIP 113368',
    id: 'Fomalhaut',
    nameEn: 'Fomalhaut',
    nameZh: '北落师门',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.16,
  },
  {
    aliases: ['天津四', '天鹅座α', 'Alpha Cygni', 'HIP 102098', 'HP 102098', 'HP102098', 'tianjinsi', 'tjs'],
    category: 'stars',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'α Cyg / HIP 102098',
    id: 'Deneb',
    nameEn: 'Deneb',
    nameZh: '天津四',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.25,
  },
  {
    aliases: ['十字架三', '南十字座β', 'Beta Crucis', 'Mimosa', 'HIP 62434', 'HP 62434', 'HP62434', 'shizijiasan', 'szjs'],
    category: 'stars',
    constellationEn: 'Crux',
    constellationZh: '南十字座',
    designation: 'β Cru / HIP 62434',
    id: 'Mimosa',
    nameEn: 'Mimosa',
    nameZh: '十字架三',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.25,
  },
  {
    aliases: ['轩辕十四', '狮子座α', 'Alpha Leonis', 'HIP 49669', 'HP 49669', 'HP49669', 'xuanyuanshisi', 'xyss'],
    category: 'stars',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'α Leo / HIP 49669',
    id: 'Regulus',
    nameEn: 'Regulus',
    nameZh: '轩辕十四',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.35,
  },
  {
    aliases: ['北河二', '双子座α', 'Alpha Geminorum', 'HIP 36850', 'HP 36850', 'HP36850', 'beiheer', 'bhe'],
    category: 'stars',
    constellationEn: 'Gemini',
    constellationZh: '双子座',
    designation: 'α Gem / HIP 36850',
    id: 'Castor',
    nameEn: 'Castor',
    nameZh: '北河二',
    typeEn: 'Star System',
    typeZh: '恒星',
    vmag: 1.58,
  },
  {
    aliases: ['北极星', '小熊座α', 'Alpha Ursae Minoris', '勾陈一', 'North Star', 'Polaris', 'HIP 11767', 'HP 11767', 'HP11767', 'beijixing', 'bjx'],
    category: 'stars',
    constellationEn: 'Ursa Minor',
    constellationZh: '小熊座',
    designation: 'α UMi / HIP 11767',
    id: 'Polaris',
    nameEn: 'Polaris',
    nameZh: '北极星',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.98,
  },
  {
    aliases: ['大陵五', '英仙座β', 'Beta Persei', 'Demon Star', '恶魔星', 'HIP 14576', 'HP 14576', 'HP14576', 'dalingwu', 'dlw'],
    category: 'stars',
    constellationEn: 'Perseus',
    constellationZh: '英仙座',
    designation: 'β Per / HIP 14576',
    id: 'Algol',
    nameEn: 'Algol',
    nameZh: '大陵五',
    typeEn: 'Eclipsing Binary',
    typeZh: '食双星',
    vmag: 2.12,
  },
  // Big Dipper (北斗七星)
  {
    aliases: ['北斗一', '天枢', '大熊座α', 'Alpha Ursae Majoris', 'HIP 54061', 'HP 54061', 'HP54061', 'tianshu', 'ts'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'α UMa / HIP 54061',
    id: 'Dubhe',
    nameEn: 'Dubhe',
    nameZh: '天枢 (北斗一)',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.79,
  },
  {
    aliases: ['北斗二', '天璇', '大熊座β', 'Beta Ursae Majoris', 'HIP 53910', 'HP 53910', 'HP53910', 'tianxuan', 'tx'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'β UMa / HIP 53910',
    id: 'Merak',
    nameEn: 'Merak',
    nameZh: '天璇 (北斗二)',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 2.37,
  },
  {
    aliases: ['北斗三', '天玑', '大熊座γ', 'Gamma Ursae Majoris', 'HIP 58001', 'HP 58001', 'HP58001', 'tianji', 'tj'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'γ UMa / HIP 58001',
    id: 'Phecda',
    nameEn: 'Phecda',
    nameZh: '天玑 (北斗三)',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 2.44,
  },
  {
    aliases: ['北斗四', '天权', '大熊座δ', 'Delta Ursae Majoris', 'HIP 59774', 'HP 59774', 'HP59774', 'tianquan', 'tq'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'δ UMa / HIP 59774',
    engineIds: ['* del UMa'],
    id: 'Megrez',
    nameEn: 'Megrez',
    nameZh: '天权 (北斗四)',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 3.31,
  },
  {
    aliases: ['北斗五', '玉衡', '大熊座ε', 'Epsilon Ursae Majoris', 'HIP 62956', 'HP 62956', 'HP62956', 'yuheng', 'yh'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'ε UMa / HIP 62956',
    id: 'Alioth',
    nameEn: 'Alioth',
    nameZh: '玉衡 (北斗五)',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.77,
  },
  {
    aliases: ['北斗六', '开阳', '大熊座ζ', 'Zeta Ursae Majoris', 'HIP 65378', 'HP 65378', 'HP65378', 'kaiyang', 'ky'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'ζ UMa / HIP 65378',
    engineIds: ['* zet UMa'],
    id: 'Mizar',
    nameEn: 'Mizar',
    nameZh: '开阳 (北斗六)',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 2.23,
  },
  {
    aliases: ['北斗七', '摇光', '大熊座η', 'Eta Ursae Majoris', 'HIP 67301', 'HP 67301', 'HP67301', 'yaoguang', 'yg'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'η UMa / HIP 67301',
    id: 'Alkaid',
    nameEn: 'Alkaid',
    nameZh: '摇光 (北斗七)',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.86,
  },
  {
    aliases: ['开阳增一', '辅星', '大熊座80', 'Alcor', 'HIP 65477', 'HP 65477', 'HP65477', 'fuxing', 'fx'],
    category: 'stars',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: '80 UMa / HIP 65477',
    engineIds: ['* 80 UMa'],
    id: 'Alcor',
    nameEn: 'Alcor',
    nameZh: '辅星 (开阳增一)',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 4.01,
  },
  // Additional Bright & Notable Stars (HIP & Bayer Identifiers)
  {
    aliases: ['参宿五', '猎户座γ', 'Gamma Orionis', 'Bellatrix', 'HIP 25336', 'HP 25336', 'HP25336', 'shensuwu', 'ssw'],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'γ Ori / HIP 25336',
    id: 'Bellatrix',
    nameEn: 'Bellatrix',
    nameZh: '参宿五',
    typeEn: 'Blue Giant',
    typeZh: '蓝巨星',
    vmag: 1.64,
  },
  {
    aliases: ['参宿二', '猎户座ε', 'Epsilon Orionis', 'Alnilam', 'HIP 26311', 'HP 26311', 'HP26311', 'shensuer', 'sse'],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'ε Ori / HIP 26311',
    id: 'Alnilam',
    nameEn: 'Alnilam',
    nameZh: '参宿二',
    typeEn: 'Blue Supergiant',
    typeZh: '蓝超巨星',
    vmag: 1.69,
  },
  {
    aliases: ['参宿一', '猎户座ζ', 'Zeta Orionis', 'Alnitak', 'HIP 26727', 'HP 26727', 'HP26727', 'shensuyi', 'ssy'],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'ζ Ori / HIP 26727',
    id: 'Alnitak',
    nameEn: 'Alnitak',
    nameZh: '参宿一',
    typeEn: 'Star System',
    typeZh: '恒星系统',
    vmag: 1.77,
  },
  {
    aliases: ['参宿三', '猎户座δ', 'Delta Orionis', 'Mintaka', 'HIP 25930', 'HP 25930', 'HP25930', 'shensusan', 'sss'],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'δ Ori / HIP 25930',
    id: 'Mintaka',
    nameEn: 'Mintaka',
    nameZh: '参宿三',
    typeEn: 'Star System',
    typeZh: '恒星系统',
    vmag: 2.23,
  },
  {
    aliases: ['参宿六', '猎户座κ', 'Kappa Orionis', 'Saiph', 'HIP 27366', 'HP 27366', 'HP27366', 'shensuliu', 'ssl'],
    category: 'stars',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'κ Ori / HIP 27366',
    id: 'Saiph',
    nameEn: 'Saiph',
    nameZh: '参宿六',
    typeEn: 'Supergiant',
    typeZh: '超巨星',
    vmag: 2.07,
  },
  {
    aliases: ['弧矢七', '大犬座ε', 'Epsilon Canis Majoris', 'Adhara', 'HIP 33579', 'HP 33579', 'HP33579', 'hushiqi', 'hsq'],
    category: 'stars',
    constellationEn: 'Canis Major',
    constellationZh: '大犬座',
    designation: 'ε CMa / HIP 33579',
    id: 'Adhara',
    nameEn: 'Adhara',
    nameZh: '弧矢七',
    popular: true,
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.50,
  },
  {
    aliases: ['弧矢一', '大犬座δ', 'Delta Canis Majoris', 'Wezen', 'HIP 34444', 'HP 34444', 'HP34444', 'hushiyi', 'hsy'],
    category: 'stars',
    constellationEn: 'Canis Major',
    constellationZh: '大犬座',
    designation: 'δ CMa / HIP 34444',
    id: 'Wezen',
    nameEn: 'Wezen',
    nameZh: '弧矢一',
    typeEn: 'Supergiant',
    typeZh: '超巨星',
    vmag: 1.83,
  },
  {
    aliases: ['军市一', '大犬座β', 'Beta Canis Majoris', 'Mirzam', 'HIP 30324', 'HP 30324', 'HP30324', 'junshiyi', 'jsy'],
    category: 'stars',
    constellationEn: 'Canis Major',
    constellationZh: '大犬座',
    designation: 'β CMa / HIP 30324',
    id: 'Mirzam',
    nameEn: 'Mirzam',
    nameZh: '军市一',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 1.98,
  },
  {
    aliases: ['辇道增七', '天鹅座β', 'Beta Cygni', 'Albireo', 'HIP 95947', 'HP 95947', 'HP95947', 'niandaozengqi', 'ndzq'],
    category: 'stars',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'β Cyg / HIP 95947',
    engineIds: ['* bet01 Cyg'],
    id: 'Albireo',
    nameEn: 'Albireo',
    nameZh: '辇道增七',
    popular: true,
    typeEn: 'Binary Star',
    typeZh: '双星',
    vmag: 3.05,
  },
  {
    aliases: ['天津一', '天鹅座γ', 'Gamma Cygni', 'Sadr', 'HIP 100453', 'HP 100453', 'HP100453', 'tianjinyi', 'tjy'],
    category: 'stars',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'γ Cyg / HIP 100453',
    engineIds: ['* gam Cyg'],
    id: 'Sadr',
    nameEn: 'Sadr',
    nameZh: '天津一',
    typeEn: 'Supergiant',
    typeZh: '超巨星',
    vmag: 2.23,
  },
  {
    aliases: ['天津九', '天鹅座ε', 'Epsilon Cygni', 'Gienah', 'HIP 102488', 'HP 102488', 'HP102488', 'tianjinjiu', 'tjj'],
    category: 'stars',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'ε Cyg / HIP 102488',
    id: 'Gienah',
    nameEn: 'Gienah',
    nameZh: '天津九',
    typeEn: 'Giant Star',
    typeZh: '巨星',
    vmag: 2.48,
  },
  {
    aliases: ['帝', '北极二', '小熊座β', 'Beta Ursae Minoris', 'Kochab', 'HIP 72607', 'HP 72607', 'HP72607', 'beijier', 'bje'],
    category: 'stars',
    constellationEn: 'Ursa Minor',
    constellationZh: '小熊座',
    designation: 'β UMi / HIP 72607',
    id: 'Kochab',
    nameEn: 'Kochab',
    nameZh: '帝 (北极二)',
    typeEn: 'Giant Star',
    typeZh: '巨星',
    vmag: 2.08,
  },
  {
    aliases: ['娄宿三', '白羊座α', 'Alpha Arietis', 'Hamal', 'HIP 9884', 'HP 9884', 'HP9884', 'loushusan', 'lss'],
    category: 'stars',
    constellationEn: 'Aries',
    constellationZh: '白羊座',
    designation: 'α Ari / HIP 9884',
    id: 'Hamal',
    nameEn: 'Hamal',
    nameZh: '娄宿三',
    typeEn: 'Giant Star',
    typeZh: '巨星',
    vmag: 2.01,
  },
  {
    aliases: ['奎宿九', '仙女座β', 'Beta Andromedae', 'Mirach', 'HIP 5447', 'HP 5447', 'HP5447', 'kuishujiu', 'ksj'],
    category: 'stars',
    constellationEn: 'Andromeda',
    constellationZh: '仙女座',
    designation: 'β And / HIP 5447',
    id: 'Mirach',
    nameEn: 'Mirach',
    nameZh: '奎宿九',
    typeEn: 'Red Giant',
    typeZh: '红巨星',
    vmag: 2.07,
  },
  {
    aliases: ['天大将军一', '仙女座γ', 'Gamma Andromedae', 'Almach', 'HIP 9640', 'HP 9640', 'HP9640', 'tiandajiangjunyi', 'tdjjy'],
    category: 'stars',
    constellationEn: 'Andromeda',
    constellationZh: '仙女座',
    designation: 'γ And / HIP 9640',
    id: 'Almach',
    nameEn: 'Almach',
    nameZh: '天大将军一',
    typeEn: 'Multiple Star',
    typeZh: '多恒星系统',
    vmag: 2.10,
  },
  {
    aliases: ['室宿一', '飞马座α', 'Alpha Pegasi', 'Markab', 'HIP 113963', 'HP 113963', 'HP113963', 'shishuyi', 'ssy'],
    category: 'stars',
    constellationEn: 'Pegasus',
    constellationZh: '飞马座',
    designation: 'α Peg / HIP 113963',
    id: 'Markab',
    nameEn: 'Markab',
    nameZh: '室宿一',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 2.49,
  },
  {
    aliases: ['室宿二', '飞马座β', 'Beta Pegasi', 'Scheat', 'HIP 113881', 'HP 113881', 'HP113881', 'shishuer', 'sse'],
    category: 'stars',
    constellationEn: 'Pegasus',
    constellationZh: '飞马座',
    designation: 'β Peg / HIP 113881',
    id: 'Scheat',
    nameEn: 'Scheat',
    nameZh: '室宿二',
    typeEn: 'Red Giant',
    typeZh: '红巨星',
    vmag: 2.42,
  },
  {
    aliases: ['壁宿一', '飞马座γ', 'Gamma Pegasi', 'Algenib', 'HIP 1067', 'HP 1067', 'HP1067', 'bishuyi', 'bsy'],
    category: 'stars',
    constellationEn: 'Pegasus',
    constellationZh: '飞马座',
    designation: 'γ Peg / HIP 1067',
    engineIds: ['* gam Peg'],
    id: 'Algenib',
    nameEn: 'Algenib',
    nameZh: '壁宿一',
    typeEn: 'Subgiant',
    typeZh: '次巨星',
    vmag: 2.84,
  },
  {
    aliases: ['危宿三', '飞马座ε', 'Epsilon Pegasi', 'Enif', 'HIP 107315', 'HP 107315', 'HP107315', 'weishusan', 'wss'],
    category: 'stars',
    constellationEn: 'Pegasus',
    constellationZh: '飞马座',
    designation: 'ε Peg / HIP 107315',
    id: 'Enif',
    nameEn: 'Enif',
    nameZh: '危宿三',
    typeEn: 'Supergiant',
    typeZh: '超巨星',
    vmag: 2.38,
  },
  {
    aliases: ['尾宿八', '天蝎座λ', 'Lambda Scorpii', 'Shaula', 'HIP 85927', 'HP 85927', 'HP85927', 'weishuba', 'wsb'],
    category: 'stars',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'λ Sco / HIP 85927',
    id: 'Shaula',
    nameEn: 'Shaula',
    nameZh: '尾宿八',
    popular: true,
    typeEn: 'Multiple Star',
    typeZh: '多恒星系统',
    vmag: 1.62,
  },
  {
    aliases: ['尾宿五', '天蝎座θ', 'Theta Scorpii', 'Sargas', 'HIP 86228', 'HP 86228', 'HP86228', 'weishuwu', 'wsw'],
    category: 'stars',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'θ Sco / HIP 86228',
    id: 'Sargas',
    nameEn: 'Sargas',
    nameZh: '尾宿五',
    typeEn: 'Bright Giant',
    typeZh: '亮巨星',
    vmag: 1.86,
  },
  {
    aliases: ['房宿三', '天蝎座δ', 'Delta Scorpii', 'Dschubba', 'HIP 78401', 'HP 78401', 'HP78401', 'fangshusan', 'fss'],
    category: 'stars',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'δ Sco / HIP 78401',
    id: 'Dschubba',
    nameEn: 'Dschubba',
    nameZh: '房宿三',
    typeEn: 'Subgiant',
    typeZh: '次巨星',
    vmag: 2.29,
  },
  {
    aliases: ['箕宿三', '人马座ε', 'Epsilon Sagittarii', 'Kaus Australis', 'HIP 90185', 'HP 90185', 'HP90185', 'jishusan', 'jss'],
    category: 'stars',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'ε Sgr / HIP 90185',
    id: 'Kaus Australis',
    nameEn: 'Kaus Australis',
    nameZh: '箕宿三',
    popular: true,
    typeEn: 'Giant Star',
    typeZh: '巨星',
    vmag: 1.79,
  },
  {
    aliases: ['斗宿四', '人马座σ', 'Sigma Sagittarii', 'Nunki', 'HIP 92855', 'HP 92855', 'HP92855', 'doushusi', 'dss'],
    category: 'stars',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'σ Sgr / HIP 92855',
    id: 'Nunki',
    nameEn: 'Nunki',
    nameZh: '斗宿四',
    typeEn: 'Subgiant',
    typeZh: '次巨星',
    vmag: 2.05,
  },
  {
    aliases: ['五车三', '御夫座β', 'Beta Aurigae', 'Menkalinan', 'HIP 28360', 'HP 28360', 'HP28360', 'wuchesan', 'wcs'],
    category: 'stars',
    constellationEn: 'Auriga',
    constellationZh: '御夫座',
    designation: 'β Aur / HIP 28360',
    id: 'Menkalinan',
    nameEn: 'Menkalinan',
    nameZh: '五车三',
    typeEn: 'Subgiant',
    typeZh: '次巨星',
    vmag: 1.90,
  },
  {
    aliases: ['十字架一', '南十字座γ', 'Gamma Crucis', 'Gacrux', 'HIP 61084', 'HP 61084', 'HP61084', 'shizijiayi', 'szjy'],
    category: 'stars',
    constellationEn: 'Crux',
    constellationZh: '南十字座',
    designation: 'γ Cru / HIP 61084',
    id: 'Gacrux',
    nameEn: 'Gacrux',
    nameZh: '十字架一',
    typeEn: 'Red Giant',
    typeZh: '红巨星',
    vmag: 1.64,
  },
  {
    aliases: ['候', '天市右垣十一', '蛇夫座α', 'Alpha Ophiuchi', 'Rasalhague', 'HIP 86032', 'HP 86032', 'HP86032', 'tianshiras'],
    category: 'stars',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'α Oph / HIP 86032',
    id: 'Rasalhague',
    nameEn: 'Rasalhague',
    nameZh: '候 (天市右垣十一)',
    typeEn: 'Giant Star',
    typeZh: '巨星',
    vmag: 2.08,
  },
  {
    aliases: ['贯索四', '北冕座α', 'Alpha Coronae Borealis', 'Alphecca', 'Gemma', 'HIP 76267', 'HP 76267', 'HP76267', 'guansuosi', 'gss'],
    category: 'stars',
    constellationEn: 'Corona Borealis',
    constellationZh: '北冕座',
    designation: 'α CrB / HIP 76267',
    id: 'Alphecca',
    nameEn: 'Alphecca',
    nameZh: '贯索四',
    typeEn: 'Eclipsing Binary',
    typeZh: '食双星',
    vmag: 2.22,
  },
  {
    aliases: ['天囷一', '鲸鱼座α', 'Alpha Ceti', 'Menkar', 'HIP 14146', 'HP 14146', 'HP14146', 'tianqunyi', 'tqy'],
    category: 'stars',
    constellationEn: 'Cetus',
    constellationZh: '鲸鱼座',
    designation: 'α Cet / HIP 14146',
    id: 'Menkar',
    nameEn: 'Menkar',
    nameZh: '天囷一',
    typeEn: 'Red Giant',
    typeZh: '红巨星',
    vmag: 2.54,
  },
  {
    aliases: ['五帝座一', '狮子座β', 'Beta Leonis', 'Denebola', 'HIP 57632', 'HP 57632', 'HP57632', 'wudizuoyi', 'wdzy'],
    category: 'stars',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'β Leo / HIP 57632',
    id: 'Denebola',
    nameEn: 'Denebola',
    nameZh: '五帝座一',
    typeEn: 'Star',
    typeZh: '恒星',
    vmag: 2.14,
  },
];
