import type { CelestialSearchItem } from './celestial-catalog';

export const MESSIER_OBJECTS: CelestialSearchItem[] = [
  {
    aliases: ['蟹状星云', 'Crab Nebula', 'NGC 1952', 'M1', 'm1', 'xiezhuangxingyun', 'xzxy'],
    category: 'dso',
    constellationEn: 'Taurus',
    constellationZh: '金牛座',
    designation: 'NGC 1952',
    id: 'M 1',
    nameEn: 'Crab Nebula (M1)',
    nameZh: '蟹状星云 (M1)',
    popular: true,
    typeEn: 'Supernova Remnant',
    typeZh: '超新星遗迹',
    vmag: 8.4,
  },
  {
    aliases: ['宝瓶座球状星团', 'NGC 7089', 'M2', 'm2'],
    category: 'dso',
    constellationEn: 'Aquarius',
    constellationZh: '宝瓶座',
    designation: 'NGC 7089',
    id: 'M 2',
    nameEn: 'Globular Cluster (M2)',
    nameZh: '宝瓶座球状星团 (M2)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.3,
  },
  {
    aliases: ['猎犬座球状星团', 'NGC 5272', 'M3', 'm3'],
    category: 'dso',
    constellationEn: 'Canes Venatici',
    constellationZh: '猎犬座',
    designation: 'NGC 5272',
    id: 'M 3',
    nameEn: 'Globular Cluster (M3)',
    nameZh: '猎犬座球状星团 (M3)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.2,
  },
  {
    aliases: ['天蝎座球状星团', 'NGC 6121', 'M4', 'm4'],
    category: 'dso',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'NGC 6121',
    id: 'M 4',
    nameEn: 'Globular Cluster (M4)',
    nameZh: '天蝎座球状星团 (M4)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 5.6,
  },
  {
    aliases: ['巨蛇座球状星团', '玫瑰星团', 'Rose Cluster', 'NGC 5904', 'M5', 'm5'],
    category: 'dso',
    constellationEn: 'Serpens',
    constellationZh: '巨蛇座',
    designation: 'NGC 5904',
    id: 'M 5',
    nameEn: 'Globular Cluster (M5)',
    nameZh: '巨蛇座球状星团 (M5)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 5.6,
  },
  {
    aliases: ['蝴蝶星团', 'Butterfly Cluster', 'NGC 6405', 'M6', 'm6', 'hudiexingtuan', 'hdxt'],
    category: 'dso',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'NGC 6405',
    id: 'M 6',
    nameEn: 'Butterfly Cluster (M6)',
    nameZh: '蝴蝶星团 (M6)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 4.2,
  },
  {
    aliases: ['托勒密星团', 'Ptolemy\'s Cluster', 'NGC 6475', 'M7', 'm7', 'tuolemexingtuan'],
    category: 'dso',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'NGC 6475',
    id: 'M 7',
    nameEn: 'Ptolemy\'s Cluster (M7)',
    nameZh: '托勒密星团 (M7)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 3.3,
  },
  {
    aliases: ['礁湖星云', 'Lagoon Nebula', 'NGC 6523', 'M8', 'm8', 'jiaohuxingyun', 'jhxy'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6523',
    id: 'M 8',
    nameEn: 'Lagoon Nebula (M8)',
    nameZh: '礁湖星云 (M8)',
    popular: true,
    typeEn: 'Emission Nebula',
    typeZh: '发射星云',
    vmag: 6.0,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6333', 'M9', 'm9'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6333',
    id: 'M 9',
    nameEn: 'Globular Cluster (M9)',
    nameZh: '蛇夫座球状星团 (M9)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.7,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6254', 'M10', 'm10'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6254',
    id: 'M 10',
    nameEn: 'Globular Cluster (M10)',
    nameZh: '蛇夫座球状星团 (M10)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.4,
  },
  {
    aliases: ['野鸭星团', 'Wild Duck Cluster', 'NGC 6705', 'M11', 'm11', 'yeyaxingtuan', 'yyxt'],
    category: 'dso',
    constellationEn: 'Scutum',
    constellationZh: '盾牌座',
    designation: 'NGC 6705',
    id: 'M 11',
    nameEn: 'Wild Duck Cluster (M11)',
    nameZh: '野鸭星团 (M11)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.8,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6218', 'M12', 'm12'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6218',
    id: 'M 12',
    nameEn: 'Globular Cluster (M12)',
    nameZh: '蛇夫座球状星团 (M12)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.7,
  },
  {
    aliases: ['武仙座球状星团', 'Hercules Cluster', 'Great Hercules Cluster', 'NGC 6205', 'M13', 'm13', 'wuxianzuoqiuzhuangxingtuan'],
    category: 'dso',
    constellationEn: 'Hercules',
    constellationZh: '武仙座',
    designation: 'NGC 6205',
    id: 'M 13',
    nameEn: 'Hercules Globular Cluster (M13)',
    nameZh: '武仙座球状星团 (M13)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 5.8,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6402', 'M14', 'm14'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6402',
    id: 'M 14',
    nameEn: 'Globular Cluster (M14)',
    nameZh: '蛇夫座球状星团 (M14)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.6,
  },
  {
    aliases: ['飞马座球状星团', 'Great Pegasus Cluster', 'NGC 7078', 'M15', 'm15'],
    category: 'dso',
    constellationEn: 'Pegasus',
    constellationZh: '飞马座',
    designation: 'NGC 7078',
    id: 'M 15',
    nameEn: 'Pegasus Cluster (M15)',
    nameZh: '飞马座球状星团 (M15)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.2,
  },
  {
    aliases: ['鹰状星云', 'Eagle Nebula', '创生之柱', 'Pillars of Creation', 'NGC 6611', 'M16', 'm16', 'yingzhuangxingyun', 'yzxy'],
    category: 'dso',
    constellationEn: 'Serpens',
    constellationZh: '巨蛇座',
    designation: 'NGC 6611',
    id: 'M 16',
    nameEn: 'Eagle Nebula (M16)',
    nameZh: '鹰状星云 (M16)',
    popular: true,
    typeEn: 'Emission Nebula',
    typeZh: '发射星云',
    vmag: 6.4,
  },
  {
    aliases: ['欧米伽星云', '天鹅星云', 'Omega Nebula', 'Swan Nebula', 'NGC 6618', 'M17', 'm17', 'oumiejiaxingyun', 'omjxy'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6618',
    id: 'M 17',
    nameEn: 'Omega Nebula (M17)',
    nameZh: '欧米伽星云 (M17)',
    popular: true,
    typeEn: 'Emission Nebula',
    typeZh: '发射星云',
    vmag: 6.0,
  },
  {
    aliases: ['黑天鹅星团', 'Black Swan Cluster', 'NGC 6613', 'M18', 'm18'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6613',
    id: 'M 18',
    nameEn: 'Open Cluster (M18)',
    nameZh: '人马座疏散星团 (M18)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 7.5,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6273', 'M19', 'm19'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6273',
    id: 'M 19',
    nameEn: 'Globular Cluster (M19)',
    nameZh: '蛇夫座球状星团 (M19)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.8,
  },
  {
    aliases: ['三叶星云', '三裂星云', 'Trifid Nebula', 'NGC 6514', 'M20', 'm20', 'sanyexingyun', 'syxy'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6514',
    id: 'M 20',
    nameEn: 'Trifid Nebula (M20)',
    nameZh: '三叶星云 (M20)',
    popular: true,
    typeEn: 'Emission / Reflection Nebula',
    typeZh: '发射与反射星云',
    vmag: 6.3,
  },
  {
    aliases: ['人马座疏散星团', 'NGC 6531', 'M21', 'm21'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6531',
    id: 'M 21',
    nameEn: 'Open Cluster (M21)',
    nameZh: '人马座疏散星团 (M21)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.5,
  },
  {
    aliases: ['人马座大球状星团', 'Great Sagittarius Cluster', 'NGC 6656', 'M22', 'm22'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6656',
    id: 'M 22',
    nameEn: 'Sagittarius Cluster (M22)',
    nameZh: '人马座大球状星团 (M22)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 5.1,
  },
  {
    aliases: ['人马座疏散星团', 'NGC 6494', 'M23', 'm23'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6494',
    id: 'M 23',
    nameEn: 'Open Cluster (M23)',
    nameZh: '人马座疏散星团 (M23)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.5,
  },
  {
    aliases: ['人马座恒星云', 'Sagittarius Star Cloud', 'Delle Caustiche', 'M24', 'm24'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'IC 4715',
    id: 'M 24',
    nameEn: 'Sagittarius Star Cloud (M24)',
    nameZh: '人马座恒星云 (M24)',
    popular: true,
    typeEn: 'Star Cloud',
    typeZh: '恒星云',
    vmag: 4.6,
  },
  {
    aliases: ['人马座疏散星团', 'IC 4725', 'M25', 'm25'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'IC 4725',
    id: 'M 25',
    nameEn: 'Open Cluster (M25)',
    nameZh: '人马座疏散星团 (M25)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 4.6,
  },
  {
    aliases: ['盾牌座疏散星团', 'NGC 6694', 'M26', 'm26'],
    category: 'dso',
    constellationEn: 'Scutum',
    constellationZh: '盾牌座',
    designation: 'NGC 6694',
    id: 'M 26',
    nameEn: 'Open Cluster (M26)',
    nameZh: '盾牌座疏散星团 (M26)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 8.0,
  },
  {
    aliases: ['哑铃星云', 'Dumbbell Nebula', 'NGC 6853', 'M27', 'm27', 'yalingxingyun', 'ylxy'],
    category: 'dso',
    constellationEn: 'Vulpecula',
    constellationZh: '狐狸座',
    designation: 'NGC 6853',
    id: 'M 27',
    nameEn: 'Dumbbell Nebula (M27)',
    nameZh: '哑铃星云 (M27)',
    popular: true,
    typeEn: 'Planetary Nebula',
    typeZh: '行星状星云',
    vmag: 7.5,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6626', 'M28', 'm28'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6626',
    id: 'M 28',
    nameEn: 'Globular Cluster (M28)',
    nameZh: '人马座球状星团 (M28)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.8,
  },
  {
    aliases: ['冷凝管星团', 'Cooling Tower', 'NGC 6913', 'M29', 'm29'],
    category: 'dso',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'NGC 6913',
    id: 'M 29',
    nameEn: 'Open Cluster (M29)',
    nameZh: '天鹅座疏散星团 (M29)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 7.1,
  },
  {
    aliases: ['水母星团', 'Jellyfish Cluster', 'NGC 7099', 'M30', 'm30'],
    category: 'dso',
    constellationEn: 'Capricornus',
    constellationZh: '摩羯座',
    designation: 'NGC 7099',
    id: 'M 30',
    nameEn: 'Globular Cluster (M30)',
    nameZh: '摩羯座球状星团 (M30)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.2,
  },
  {
    aliases: ['仙女座大星系', '仙女座星系', 'Andromeda Galaxy', 'NGC 224', 'M31', 'm31', 'xiannvzuodaxingxi', 'xnzdxi'],
    category: 'dso',
    constellationEn: 'Andromeda',
    constellationZh: '仙女座',
    designation: 'NGC 224',
    id: 'M 31',
    nameEn: 'Andromeda Galaxy (M31)',
    nameZh: '仙女座大星系 (M31)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 3.44,
  },
  {
    aliases: ['仙女座伴星系', 'NGC 221', 'M32', 'm32'],
    category: 'dso',
    constellationEn: 'Andromeda',
    constellationZh: '仙女座',
    designation: 'NGC 221',
    id: 'M 32',
    nameEn: 'Elliptical Galaxy (M32)',
    nameZh: '仙女座伴星系 (M32)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 8.1,
  },
  {
    aliases: ['三角座星系', 'Triangulum Galaxy', 'NGC 598', 'M33', 'm33', 'sanjiaozuoxingxi', 'sjzxx'],
    category: 'dso',
    constellationEn: 'Triangulum',
    constellationZh: '三角座',
    designation: 'NGC 598',
    id: 'M 33',
    nameEn: 'Triangulum Galaxy (M33)',
    nameZh: '三角座星系 (M33)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 5.7,
  },
  {
    aliases: ['英仙座疏散星团', 'NGC 1039', 'M34', 'm34'],
    category: 'dso',
    constellationEn: 'Perseus',
    constellationZh: '英仙座',
    designation: 'NGC 1039',
    id: 'M 34',
    nameEn: 'Open Cluster (M34)',
    nameZh: '英仙座疏散星团 (M34)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.5,
  },
  {
    aliases: ['鞋扣星团', 'Shoe-Buckle Cluster', 'NGC 2168', 'M35', 'm35'],
    category: 'dso',
    constellationEn: 'Gemini',
    constellationZh: '双子座',
    designation: 'NGC 2168',
    id: 'M 35',
    nameEn: 'Open Cluster (M35)',
    nameZh: '双子座疏散星团 (M35)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.3,
  },
  {
    aliases: ['风车星团', 'Pinwheel Cluster', 'NGC 1960', 'M36', 'm36'],
    category: 'dso',
    constellationEn: 'Auriga',
    constellationZh: '御夫座',
    designation: 'NGC 1960',
    id: 'M 36',
    nameEn: 'Pinwheel Cluster (M36)',
    nameZh: '风车星团 (M36)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.3,
  },
  {
    aliases: ['御夫座疏散星团', 'NGC 2099', 'M37', 'm37'],
    category: 'dso',
    constellationEn: 'Auriga',
    constellationZh: '御夫座',
    designation: 'NGC 2099',
    id: 'M 37',
    nameEn: 'Open Cluster (M37)',
    nameZh: '御夫座疏散星团 (M37)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.2,
  },
  {
    aliases: ['海星星团', 'Starfish Cluster', 'NGC 1912', 'M38', 'm38'],
    category: 'dso',
    constellationEn: 'Auriga',
    constellationZh: '御夫座',
    designation: 'NGC 1912',
    id: 'M 38',
    nameEn: 'Starfish Cluster (M38)',
    nameZh: '海星星团 (M38)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 7.4,
  },
  {
    aliases: ['天鹅座疏散星团', 'NGC 7092', 'M39', 'm39'],
    category: 'dso',
    constellationEn: 'Cygnus',
    constellationZh: '天鹅座',
    designation: 'NGC 7092',
    id: 'M 39',
    nameEn: 'Open Cluster (M39)',
    nameZh: '天鹅座疏散星团 (M39)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 4.6,
  },
  {
    aliases: ['温尼克4', 'Winnecke 4', 'WNC 4', 'M40', 'm40', 'winnieke4'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'Winnecke 4',
    id: 'M 40',
    nameEn: 'Winnecke 4 (M40)',
    nameZh: '温尼克4 (M40)',
    typeEn: 'Double Star',
    typeZh: '双星',
    vmag: 9.6,
  },
  {
    aliases: ['大犬座疏散星团', '小蜂巢星团', 'NGC 2287', 'M41', 'm41'],
    category: 'dso',
    constellationEn: 'Canis Major',
    constellationZh: '大犬座',
    designation: 'NGC 2287',
    id: 'M 41',
    nameEn: 'Open Cluster (M41)',
    nameZh: '大犬座疏散星团 (M41)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 4.5,
  },
  {
    aliases: ['猎户座大星云', 'Orion Nebula', 'NGC 1976', 'M42', 'm42', 'liehuozuodaxingyun', 'lhzdxy'],
    category: 'dso',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'NGC 1976',
    id: 'M 42',
    nameEn: 'Orion Nebula (M42)',
    nameZh: '猎户座大星云 (M42)',
    popular: true,
    typeEn: 'Diffuse Nebula',
    typeZh: '弥散星云',
    vmag: 4.0,
  },
  {
    aliases: ['德梅朗星云', 'De Mairan\'s Nebula', 'NGC 1982', 'M43', 'm43', 'demeilangxingyun', 'dmlxy'],
    category: 'dso',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'NGC 1982',
    id: 'M 43',
    nameEn: 'De Mairan\'s Nebula (M43)',
    nameZh: '德梅朗星云 (M43)',
    typeEn: 'Emission Nebula',
    typeZh: '发射星云',
    vmag: 9.0,
  },
  {
    aliases: ['蜂巢星团', '鬼星团', 'Praesepe', 'Beehive Cluster', 'NGC 2632', 'M44', 'm44', 'fenghaoxingtuan', 'fhxt', 'guixingtuan'],
    category: 'dso',
    constellationEn: 'Cancer',
    constellationZh: '巨蟹座',
    designation: 'NGC 2632',
    id: 'M 44',
    nameEn: 'Beehive Cluster (M44)',
    nameZh: '蜂巢星团 (M44)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 3.7,
  },
  {
    aliases: ['昴星团', '七姐妹星团', 'Pleiades', 'Seven Sisters', 'M45', 'm45', 'maoxingtuan', 'mxt', 'qijiemeixingtuan'],
    category: 'dso',
    constellationEn: 'Taurus',
    constellationZh: '金牛座',
    designation: 'Melotte 22',
    id: 'M 45',
    nameEn: 'Pleiades (M45)',
    nameZh: '昴星团 (M45)',
    popular: true,
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 1.6,
  },
  {
    aliases: ['船尾座疏散星团', 'NGC 2437', 'M46', 'm46'],
    category: 'dso',
    constellationEn: 'Puppis',
    constellationZh: '船尾座',
    designation: 'NGC 2437',
    id: 'M 46',
    nameEn: 'Open Cluster (M46)',
    nameZh: '船尾座疏散星团 (M46)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.1,
  },
  {
    aliases: ['船尾座疏散星团', 'NGC 2422', 'M47', 'm47'],
    category: 'dso',
    constellationEn: 'Puppis',
    constellationZh: '船尾座',
    designation: 'NGC 2422',
    id: 'M 47',
    nameEn: 'Open Cluster (M47)',
    nameZh: '船尾座疏散星团 (M47)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 4.2,
  },
  {
    aliases: ['长蛇座疏散星团', 'NGC 2548', 'M48', 'm48'],
    category: 'dso',
    constellationEn: 'Hydra',
    constellationZh: '长蛇座',
    designation: 'NGC 2548',
    id: 'M 48',
    nameEn: 'Open Cluster (M48)',
    nameZh: '长蛇座疏散星团 (M48)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.5,
  },
  {
    aliases: ['室女座椭圆星系', 'NGC 4472', 'M49', 'm49'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4472',
    id: 'M 49',
    nameEn: 'Elliptical Galaxy (M49)',
    nameZh: '室女座椭圆星系 (M49)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 8.4,
  },
  {
    aliases: ['心状星团', 'Heart-shaped Cluster', 'NGC 2323', 'M50', 'm50'],
    category: 'dso',
    constellationEn: 'Monoceros',
    constellationZh: '麒麟座',
    designation: 'NGC 2323',
    id: 'M 50',
    nameEn: 'Open Cluster (M50)',
    nameZh: '麒麟座疏散星团 (M50)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.9,
  },
  {
    aliases: ['涡状星系', 'Whirlpool Galaxy', 'NGC 5194', 'M51', 'm51', 'wozhuangxingxi', 'wzxx'],
    category: 'dso',
    constellationEn: 'Canes Venatici',
    constellationZh: '猎犬座',
    designation: 'NGC 5194',
    id: 'M 51',
    nameEn: 'Whirlpool Galaxy (M51)',
    nameZh: '涡状星系 (M51)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.4,
  },
  {
    aliases: ['仙后座疏散星团', '蝎子星团', 'NGC 7654', 'M52', 'm52'],
    category: 'dso',
    constellationEn: 'Cassiopeia',
    constellationZh: '仙后座',
    designation: 'NGC 7654',
    id: 'M 52',
    nameEn: 'Open Cluster (M52)',
    nameZh: '仙后座疏散星团 (M52)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 5.0,
  },
  {
    aliases: ['后发座球状星团', 'NGC 5024', 'M53', 'm53'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 5024',
    id: 'M 53',
    nameEn: 'Globular Cluster (M53)',
    nameZh: '后发座球状星团 (M53)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.6,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6715', 'M54', 'm54'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6715',
    id: 'M 54',
    nameEn: 'Globular Cluster (M54)',
    nameZh: '人马座球状星团 (M54)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.6,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6809', 'M55', 'm55'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6809',
    id: 'M 55',
    nameEn: 'Globular Cluster (M55)',
    nameZh: '人马座球状星团 (M55)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.3,
  },
  {
    aliases: ['天琴座球状星团', 'NGC 6779', 'M56', 'm56'],
    category: 'dso',
    constellationEn: 'Lyra',
    constellationZh: '天琴座',
    designation: 'NGC 6779',
    id: 'M 56',
    nameEn: 'Globular Cluster (M56)',
    nameZh: '天琴座球状星团 (M56)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 8.3,
  },
  {
    aliases: ['环状星云', 'Ring Nebula', 'NGC 6720', 'M57', 'm57', 'huanzhuangxingyun', 'hzxy'],
    category: 'dso',
    constellationEn: 'Lyra',
    constellationZh: '天琴座',
    designation: 'NGC 6720',
    id: 'M 57',
    nameEn: 'Ring Nebula (M57)',
    nameZh: '环状星云 (M57)',
    popular: true,
    typeEn: 'Planetary Nebula',
    typeZh: '行星状星云',
    vmag: 8.8,
  },
  {
    aliases: ['室女座棒旋星系', 'NGC 4579', 'M58', 'm58'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4579',
    id: 'M 58',
    nameEn: 'Barred Spiral Galaxy (M58)',
    nameZh: '室女座棒旋星系 (M58)',
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 9.7,
  },
  {
    aliases: ['室女座椭圆星系', 'NGC 4621', 'M59', 'm59'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4621',
    id: 'M 59',
    nameEn: 'Elliptical Galaxy (M59)',
    nameZh: '室女座椭圆星系 (M59)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 9.6,
  },
  {
    aliases: ['室女座椭圆星系', 'NGC 4649', 'M60', 'm60'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4649',
    id: 'M 60',
    nameEn: 'Elliptical Galaxy (M60)',
    nameZh: '室女座椭圆星系 (M60)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 8.8,
  },
  {
    aliases: ['旋涡星系', 'NGC 4303', 'M61', 'm61'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4303',
    id: 'M 61',
    nameEn: 'Spiral Galaxy (M61)',
    nameZh: '室女座旋涡星系 (M61)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.7,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6266', 'M62', 'm62'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6266',
    id: 'M 62',
    nameEn: 'Globular Cluster (M62)',
    nameZh: '蛇夫座球状星团 (M62)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.5,
  },
  {
    aliases: ['向日葵星系', 'Sunflower Galaxy', 'NGC 5055', 'M63', 'm63', 'xiangrikuixingxi'],
    category: 'dso',
    constellationEn: 'Canes Venatici',
    constellationZh: '猎犬座',
    designation: 'NGC 5055',
    id: 'M 63',
    nameEn: 'Sunflower Galaxy (M63)',
    nameZh: '向日葵星系 (M63)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.6,
  },
  {
    aliases: ['黑眼星系', 'Black Eye Galaxy', 'NGC 4826', 'M64', 'm64', 'heiyanxingxi', 'hyxx'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4826',
    id: 'M 64',
    nameEn: 'Black Eye Galaxy (M64)',
    nameZh: '黑眼星系 (M64)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.5,
  },
  {
    aliases: ['狮子座三胞胎之一', 'NGC 3623', 'M65', 'm65'],
    category: 'dso',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'NGC 3623',
    id: 'M 65',
    nameEn: 'Spiral Galaxy (M65)',
    nameZh: '狮子座旋涡星系 (M65)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.3,
  },
  {
    aliases: ['狮子座三胞胎之一', 'NGC 3627', 'M66', 'm66'],
    category: 'dso',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'NGC 3627',
    id: 'M 66',
    nameEn: 'Barred Spiral Galaxy (M66)',
    nameZh: '狮子座棒旋星系 (M66)',
    popular: true,
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 8.9,
  },
  {
    aliases: ['国王眼镜蛇星团', 'NGC 2682', 'M67', 'm67'],
    category: 'dso',
    constellationEn: 'Cancer',
    constellationZh: '巨蟹座',
    designation: 'NGC 2682',
    id: 'M 67',
    nameEn: 'Open Cluster (M67)',
    nameZh: '巨蟹座疏散星团 (M67)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.1,
  },
  {
    aliases: ['长蛇座球状星团', 'NGC 4590', 'M68', 'm68'],
    category: 'dso',
    constellationEn: 'Hydra',
    constellationZh: '长蛇座',
    designation: 'NGC 4590',
    id: 'M 68',
    nameEn: 'Globular Cluster (M68)',
    nameZh: '长蛇座球状星团 (M68)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.8,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6637', 'M69', 'm69'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6637',
    id: 'M 69',
    nameEn: 'Globular Cluster (M69)',
    nameZh: '人马座球状星团 (M69)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.6,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6681', 'M70', 'm70'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6681',
    id: 'M 70',
    nameEn: 'Globular Cluster (M70)',
    nameZh: '人马座球状星团 (M70)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.9,
  },
  {
    aliases: ['天箭座球状星团', 'NGC 6838', 'M71', 'm71'],
    category: 'dso',
    constellationEn: 'Sagitta',
    constellationZh: '天箭座',
    designation: 'NGC 6838',
    id: 'M 71',
    nameEn: 'Globular Cluster (M71)',
    nameZh: '天箭座球状星团 (M71)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 8.2,
  },
  {
    aliases: ['宝瓶座球状星团', 'NGC 6981', 'M72', 'm72'],
    category: 'dso',
    constellationEn: 'Aquarius',
    constellationZh: '宝瓶座',
    designation: 'NGC 6981',
    id: 'M 72',
    nameEn: 'Globular Cluster (M72)',
    nameZh: '宝瓶座球状星团 (M72)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 9.3,
  },
  {
    aliases: ['宝瓶座星群', 'NGC 6994', 'M73', 'm73', 'baopingzuoxingqun'],
    category: 'dso',
    constellationEn: 'Aquarius',
    constellationZh: '宝瓶座',
    designation: 'NGC 6994',
    id: 'M 73',
    nameEn: 'Asterism (M73)',
    nameZh: '宝瓶座星群 (M73)',
    typeEn: 'Asterism',
    typeZh: '星群',
    vmag: 9.0,
  },
  {
    aliases: ['幻影星系', 'Phantom Galaxy', 'NGC 628', 'M74', 'm74'],
    category: 'dso',
    constellationEn: 'Pisces',
    constellationZh: '双鱼座',
    designation: 'NGC 628',
    id: 'M 74',
    nameEn: 'Phantom Galaxy (M74)',
    nameZh: '幻影星系 (M74)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.4,
  },
  {
    aliases: ['人马座球状星团', 'NGC 6864', 'M75', 'm75'],
    category: 'dso',
    constellationEn: 'Sagittarius',
    constellationZh: '人马座',
    designation: 'NGC 6864',
    id: 'M 75',
    nameEn: 'Globular Cluster (M75)',
    nameZh: '人马座球状星团 (M75)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 8.5,
  },
  {
    aliases: ['小哑铃星云', 'Little Dumbbell Nebula', 'NGC 650', 'M76', 'm76', 'xiaoyalingxingyun'],
    category: 'dso',
    constellationEn: 'Perseus',
    constellationZh: '英仙座',
    designation: 'NGC 650',
    id: 'M 76',
    nameEn: 'Little Dumbbell Nebula (M76)',
    nameZh: '小哑铃星云 (M76)',
    typeEn: 'Planetary Nebula',
    typeZh: '行星状星云',
    vmag: 10.1,
  },
  {
    aliases: ['鲸鱼座A', 'Cetus A', 'NGC 1068', 'M77', 'm77'],
    category: 'dso',
    constellationEn: 'Cetus',
    constellationZh: '鲸鱼座',
    designation: 'NGC 1068',
    id: 'M 77',
    nameEn: 'Spiral Galaxy (M77)',
    nameZh: '鲸鱼座A星系 (M77)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.9,
  },
  {
    aliases: ['卡斯帕星云', 'Casper Nebula', 'NGC 2068', 'M78', 'm78'],
    category: 'dso',
    constellationEn: 'Orion',
    constellationZh: '猎户座',
    designation: 'NGC 2068',
    id: 'M 78',
    nameEn: 'Reflection Nebula (M78)',
    nameZh: '猎户座反射星云 (M78)',
    popular: true,
    typeEn: 'Reflection Nebula',
    typeZh: '反射星云',
    vmag: 8.3,
  },
  {
    aliases: ['天兔座球状星团', 'NGC 1904', 'M79', 'm79'],
    category: 'dso',
    constellationEn: 'Lepus',
    constellationZh: '天兔座',
    designation: 'NGC 1904',
    id: 'M 79',
    nameEn: 'Globular Cluster (M79)',
    nameZh: '天兔座球状星团 (M79)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.7,
  },
  {
    aliases: ['天蝎座球状星团', 'NGC 6093', 'M80', 'm80'],
    category: 'dso',
    constellationEn: 'Scorpius',
    constellationZh: '天蝎座',
    designation: 'NGC 6093',
    id: 'M 80',
    nameEn: 'Globular Cluster (M80)',
    nameZh: '天蝎座球状星团 (M80)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.3,
  },
  {
    aliases: ['波德星系', 'Bode\'s Galaxy', 'NGC 3031', 'M81', 'm81', 'bodexingxi', 'bdxx'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 3031',
    id: 'M 81',
    nameEn: 'Bode\'s Galaxy (M81)',
    nameZh: '波德星系 (M81)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 6.9,
  },
  {
    aliases: ['雪茄星系', 'Cigar Galaxy', 'NGC 3034', 'M82', 'm82', 'xuejiaxingxi', 'xjxx'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 3034',
    id: 'M 82',
    nameEn: 'Cigar Galaxy (M82)',
    nameZh: '雪茄星系 (M82)',
    popular: true,
    typeEn: 'Starburst Galaxy',
    typeZh: '星暴星系',
    vmag: 8.4,
  },
  {
    aliases: ['南风车星系', 'Southern Pinwheel Galaxy', 'NGC 5236', 'M83', 'm83'],
    category: 'dso',
    constellationEn: 'Hydra',
    constellationZh: '长蛇座',
    designation: 'NGC 5236',
    id: 'M 83',
    nameEn: 'Southern Pinwheel Galaxy (M83)',
    nameZh: '南风车星系 (M83)',
    popular: true,
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 7.5,
  },
  {
    aliases: ['室女座透镜星系', 'NGC 4374', 'M84', 'm84'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4374',
    id: 'M 84',
    nameEn: 'Lenticular Galaxy (M84)',
    nameZh: '室女座透镜星系 (M84)',
    typeEn: 'Lenticular Galaxy',
    typeZh: '透镜星系',
    vmag: 9.1,
  },
  {
    aliases: ['后发座透镜星系', 'NGC 4382', 'M85', 'm85'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4382',
    id: 'M 85',
    nameEn: 'Lenticular Galaxy (M85)',
    nameZh: '后发座透镜星系 (M85)',
    typeEn: 'Lenticular Galaxy',
    typeZh: '透镜星系',
    vmag: 9.1,
  },
  {
    aliases: ['室女座透镜星系', 'NGC 4406', 'M86', 'm86'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4406',
    id: 'M 86',
    nameEn: 'Lenticular Galaxy (M86)',
    nameZh: '室女座透镜星系 (M86)',
    typeEn: 'Lenticular Galaxy',
    typeZh: '透镜星系',
    vmag: 8.9,
  },
  {
    aliases: ['室女A星系', '处女座A星系', 'Virgo A', 'NGC 4486', 'M87', 'm87', 'shinvAxingxi'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4486',
    id: 'M 87',
    nameEn: 'Virgo A (M87)',
    nameZh: '室女A星系 (M87)',
    popular: true,
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 8.6,
  },
  {
    aliases: ['后发座旋涡星系', 'NGC 4501', 'M88', 'm88'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4501',
    id: 'M 88',
    nameEn: 'Spiral Galaxy (M88)',
    nameZh: '后发座旋涡星系 (M88)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.6,
  },
  {
    aliases: ['室女座椭圆星系', 'NGC 4552', 'M89', 'm89'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4552',
    id: 'M 89',
    nameEn: 'Elliptical Galaxy (M89)',
    nameZh: '室女座椭圆星系 (M89)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 9.8,
  },
  {
    aliases: ['室女座旋涡星系', 'NGC 4569', 'M90', 'm90'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4569',
    id: 'M 90',
    nameEn: 'Spiral Galaxy (M90)',
    nameZh: '室女座旋涡星系 (M90)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.5,
  },
  {
    aliases: ['后发座棒旋星系', 'NGC 4548', 'M91', 'm91'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4548',
    id: 'M 91',
    nameEn: 'Barred Spiral Galaxy (M91)',
    nameZh: '后发座棒旋星系 (M91)',
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 10.2,
  },
  {
    aliases: ['武仙座球状星团', 'NGC 6341', 'M92', 'm92'],
    category: 'dso',
    constellationEn: 'Hercules',
    constellationZh: '武仙座',
    designation: 'NGC 6341',
    id: 'M 92',
    nameEn: 'Globular Cluster (M92)',
    nameZh: '武仙座球状星团 (M92)',
    popular: true,
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 6.4,
  },
  {
    aliases: ['蝴蝶星团', 'NGC 2447', 'M93', 'm93'],
    category: 'dso',
    constellationEn: 'Puppis',
    constellationZh: '船尾座',
    designation: 'NGC 2447',
    id: 'M 93',
    nameEn: 'Open Cluster (M93)',
    nameZh: '船尾座疏散星团 (M93)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 6.0,
  },
  {
    aliases: ['鳄鱼眼星系', 'Croc\'s Eye Galaxy', 'NGC 4736', 'M94', 'm94'],
    category: 'dso',
    constellationEn: 'Canes Venatici',
    constellationZh: '猎犬座',
    designation: 'NGC 4736',
    id: 'M 94',
    nameEn: 'Croc\'s Eye Galaxy (M94)',
    nameZh: '鳄鱼眼星系 (M94)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.2,
  },
  {
    aliases: ['狮子座棒旋星系', 'NGC 3351', 'M95', 'm95'],
    category: 'dso',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'NGC 3351',
    id: 'M 95',
    nameEn: 'Barred Spiral Galaxy (M95)',
    nameZh: '狮子座棒旋星系 (M95)',
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 9.7,
  },
  {
    aliases: ['狮子座旋涡星系', 'NGC 3368', 'M96', 'm96'],
    category: 'dso',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'NGC 3368',
    id: 'M 96',
    nameEn: 'Spiral Galaxy (M96)',
    nameZh: '狮子座旋涡星系 (M96)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.2,
  },
  {
    aliases: ['枭星云', '猫头鹰星云', 'Owl Nebula', 'NGC 3587', 'M97', 'm97', 'xiaoxingyun', 'maotouyingxingyun'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 3587',
    id: 'M 97',
    nameEn: 'Owl Nebula (M97)',
    nameZh: '枭星云 (M97)',
    popular: true,
    typeEn: 'Planetary Nebula',
    typeZh: '行星状星云',
    vmag: 9.9,
  },
  {
    aliases: ['后发座旋涡星系', 'NGC 4192', 'M98', 'm98'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4192',
    id: 'M 98',
    nameEn: 'Spiral Galaxy (M98)',
    nameZh: '后发座旋涡星系 (M98)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 10.1,
  },
  {
    aliases: ['圣凯瑟琳之轮星系', 'NGC 4254', 'M99', 'm99'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4254',
    id: 'M 99',
    nameEn: 'Spiral Galaxy (M99)',
    nameZh: '后发座旋涡星系 (M99)',
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.9,
  },
  {
    aliases: ['镜像星系', 'Mirror Galaxy', 'NGC 4321', 'M100', 'm100'],
    category: 'dso',
    constellationEn: 'Coma Berenices',
    constellationZh: '后发座',
    designation: 'NGC 4321',
    id: 'M 100',
    nameEn: 'Spiral Galaxy (M100)',
    nameZh: '镜像星系 (M100)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 9.3,
  },
  {
    aliases: ['风车星系', 'Pinwheel Galaxy', 'NGC 5457', 'M101', 'm101', 'fengchexingxi', 'fcxx'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 5457',
    id: 'M 101',
    nameEn: 'Pinwheel Galaxy (M101)',
    nameZh: '风车星系 (M101)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 7.9,
  },
  {
    aliases: ['纺锤星系', 'Spindle Galaxy', 'NGC 5866', 'M102', 'm102', 'fangzhuxingxi'],
    category: 'dso',
    constellationEn: 'Draco',
    constellationZh: '天龙座',
    designation: 'NGC 5866',
    id: 'M 102',
    nameEn: 'Spindle Galaxy (M102)',
    nameZh: '纺锤星系 (M102)',
    popular: true,
    typeEn: 'Lenticular Galaxy',
    typeZh: '透镜星系',
    vmag: 9.9,
  },
  {
    aliases: ['仙后座疏散星团', 'NGC 581', 'M103', 'm103'],
    category: 'dso',
    constellationEn: 'Cassiopeia',
    constellationZh: '仙后座',
    designation: 'NGC 581',
    id: 'M 103',
    nameEn: 'Open Cluster (M103)',
    nameZh: '仙后座疏散星团 (M103)',
    typeEn: 'Open Cluster',
    typeZh: '疏散星团',
    vmag: 7.4,
  },
  {
    aliases: ['草帽星系', 'Sombrero Galaxy', 'NGC 4594', 'M104', 'm104', 'caomaoxingxi', 'cmxx'],
    category: 'dso',
    constellationEn: 'Virgo',
    constellationZh: '室女座',
    designation: 'NGC 4594',
    id: 'M 104',
    nameEn: 'Sombrero Galaxy (M104)',
    nameZh: '草帽星系 (M104)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.0,
  },
  {
    aliases: ['狮子座椭圆星系', 'NGC 3379', 'M105', 'm105'],
    category: 'dso',
    constellationEn: 'Leo',
    constellationZh: '狮子座',
    designation: 'NGC 3379',
    id: 'M 105',
    nameEn: 'Elliptical Galaxy (M105)',
    nameZh: '狮子座椭圆星系 (M105)',
    typeEn: 'Elliptical Galaxy',
    typeZh: '椭圆星系',
    vmag: 9.3,
  },
  {
    aliases: ['猎犬座旋涡星系', 'NGC 4258', 'M106', 'm106'],
    category: 'dso',
    constellationEn: 'Canes Venatici',
    constellationZh: '猎犬座',
    designation: 'NGC 4258',
    id: 'M 106',
    nameEn: 'Spiral Galaxy (M106)',
    nameZh: '猎犬座旋涡星系 (M106)',
    popular: true,
    typeEn: 'Spiral Galaxy',
    typeZh: '旋涡星系',
    vmag: 8.4,
  },
  {
    aliases: ['蛇夫座球状星团', 'NGC 6171', 'M107', 'm107'],
    category: 'dso',
    constellationEn: 'Ophiuchus',
    constellationZh: '蛇夫座',
    designation: 'NGC 6171',
    id: 'M 107',
    nameEn: 'Globular Cluster (M107)',
    nameZh: '蛇夫座球状星团 (M107)',
    typeEn: 'Globular Cluster',
    typeZh: '球状星团',
    vmag: 7.9,
  },
  {
    aliases: ['冲浪板星系', 'Surfboard Galaxy', 'NGC 3556', 'M108', 'm108'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 3556',
    id: 'M 108',
    nameEn: 'Surfboard Galaxy (M108)',
    nameZh: '冲浪板星系 (M108)',
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 10.0,
  },
  {
    aliases: ['真空吸尘器星系', 'Vacuum Cleaner Galaxy', 'NGC 3992', 'M109', 'm109'],
    category: 'dso',
    constellationEn: 'Ursa Major',
    constellationZh: '大熊座',
    designation: 'NGC 3992',
    id: 'M 109',
    nameEn: 'Barred Spiral Galaxy (M109)',
    nameZh: '大熊座棒旋星系 (M109)',
    typeEn: 'Barred Spiral Galaxy',
    typeZh: '棒旋星系',
    vmag: 9.8,
  },
  {
    aliases: ['仙女座矮星系', 'NGC 205', 'M110', 'm110'],
    category: 'dso',
    constellationEn: 'Andromeda',
    constellationZh: '仙女座',
    designation: 'NGC 205',
    id: 'M 110',
    nameEn: 'Dwarf Elliptical Galaxy (M110)',
    nameZh: '仙女座矮星系 (M110)',
    typeEn: 'Dwarf Elliptical Galaxy',
    typeZh: '矮椭圆星系',
    vmag: 8.5,
  },
];
