import type { CelestialSearchItem } from './celestial-catalog';

export const SATELLITE_OBJECTS: CelestialSearchItem[] = [
  // 1. Jovian Moons (Galilean Satellites)
  {
    aliases: ['木卫一', '伊娥', 'Io', 'Jupiter I', 'muweiyi', 'mwy'],
    category: 'satellites',
    id: 'NAME Io',
    nameEn: 'Io',
    nameZh: '木卫一',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  {
    aliases: ['木卫二', '欧罗巴', 'Europa', 'Jupiter II', 'muweier', 'mwe'],
    category: 'satellites',
    id: 'NAME Europa',
    nameEn: 'Europa',
    nameZh: '木卫二',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  {
    aliases: ['木卫三', '盖尼米德', 'Ganymede', 'Jupiter III', 'muweisan', 'mws'],
    category: 'satellites',
    id: 'NAME Ganymede',
    nameEn: 'Ganymede',
    nameZh: '木卫三',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  {
    aliases: ['木卫四', '卡利斯托', 'Callisto', 'Jupiter IV', 'muweisi', 'mws'],
    category: 'satellites',
    id: 'NAME Callisto',
    nameEn: 'Callisto',
    nameZh: '木卫四',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  // 2. Saturnian Moons
  {
    aliases: ['土卫六', '泰坦', 'Titan', 'Saturn VI', 'tuweiliu', 'twl'],
    category: 'satellites',
    id: 'NAME Titan',
    nameEn: 'Titan',
    nameZh: '土卫六',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  {
    aliases: ['土卫二', '恩克拉多斯', 'Enceladus', 'Saturn II', 'tuweier', 'twe'],
    category: 'satellites',
    id: 'NAME Enceladus',
    nameEn: 'Enceladus',
    nameZh: '土卫二',
    popular: true,
    typeEn: 'Moon',
    typeZh: '天然卫星',
  },
  // 3. Space Stations & Artificial Satellites
  {
    aliases: [
      'ISS',
      '国际空间站',
      'International Space Station',
      'Zarya',
      'guojikongjianzhan',
      'gjkjz',
      '25544',
      'NORAD 25544',
    ],
    category: 'satellites',
    id: 'ISS',
    nameEn: 'ISS (International Space Station)',
    nameZh: '国际空间站',
    popular: true,
    typeEn: 'Space Station',
    typeZh: '空间站',
  },
  {
    aliases: [
      'CSS',
      '中国空间站',
      '天宫',
      '天宫空间站',
      '天和',
      'Tiangong',
      'Tianhe',
      'zhongguokongjianzhan',
      'zgkjz',
      'tiangong',
      'tg',
      '48274',
      'NORAD 48274',
    ],
    category: 'satellites',
    id: 'CSS',
    nameEn: 'CSS (Tiangong Space Station)',
    nameZh: '中国空间站',
    popular: true,
    typeEn: 'Space Station',
    typeZh: '空间站',
  },
  // 4. Bundled Historic / Major Comets
  {
    aliases: [
      '海尔-波普',
      '海尔-波普彗星',
      '海尔波普',
      'Hale-Bopp',
      'C/1995 O1',
      'C/1995 O1 (Hale-Bopp)',
      'haierbopu',
      'hebp',
    ],
    category: 'satellites',
    id: 'C/1995 O1 (Hale-Bopp)',
    nameEn: 'Comet Hale-Bopp (C/1995 O1)',
    nameZh: '海尔-波普彗星',
    popular: true,
    typeEn: 'Comet',
    typeZh: '彗星',
  },
  {
    aliases: [
      '哈雷',
      '哈雷彗星',
      'Halley',
      'Halley\'s Comet',
      '1P',
      '1P/Halley',
      'halaixing',
      'halaohuixing',
      'hl',
    ],
    category: 'satellites',
    id: '1P/Halley',
    nameEn: 'Halley\'s Comet (1P/Halley)',
    nameZh: '哈雷彗星',
    popular: true,
    typeEn: 'Comet',
    typeZh: '彗星',
  },
];
